# Generated by Django 5.2.8 on 2025-11-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="background_context",
            field=models.TextField(
                help_text="Contextual information leading up to the research."
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="core_findings",
            field=models.TextField(help_text="The main findings of the research."),
        ),
        migrations.AlterField(
            model_name="article",
            name="future_implications",
            field=models.TextField(
                help_text="The potential implications of the research findings."
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="lead_paragraph",
            field=models.TextField(
                help_text="A concise summary of the article's main point."
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="next_steps",
            field=models.TextField(
                help_text="Suggested future research directions based on the study."
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="research_question",
            field=models.TextField(
                help_text="The primary question the research aims to answer."
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="simplified_methods",
            field=models.TextField(
                help_text="A simplified explanation of the methods used in the study."
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="study_limitations",
            field=models.TextField(
                help_text="Limitations of the study that may affect interpretation of results."
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="surprise_finding",
            field=models.TextField(
                blank=True,
                help_text="Any unexpected results from the study.",
                null=True,
            ),
        ),
    ]
