# Generated by Django 5.2.8 on 2025-11-25 14:26

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_articlepins"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleTags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("description", models.TextField()),
                ("vector", pgvector.django.vector.VectorField(dimensions=768)),
            ],
        ),
        migrations.AddField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(to="articles.articletags"),
        ),
    ]
