# Generated by Django 5.2.8 on 2025-11-25 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0005_articletags_article_tags"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ArticleTags",
            new_name="ArticleTag",
        ),
    ]
