# Generated by Django 5.2.8 on 2025-11-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0006_rename_articletags_articletag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(blank=True, to="articles.articletag"),
        ),
    ]
