# Generated by Django 5.2.8 on 2025-11-27 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0007_alter_article_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="background_context",
        ),
        migrations.RemoveField(
            model_name="article",
            name="core_findings",
        ),
        migrations.RemoveField(
            model_name="article",
            name="future_implications",
        ),
        migrations.RemoveField(
            model_name="article",
            name="next_steps",
        ),
        migrations.RemoveField(
            model_name="article",
            name="research_question",
        ),
        migrations.RemoveField(
            model_name="article",
            name="simplified_methods",
        ),
        migrations.RemoveField(
            model_name="article",
            name="study_limitations",
        ),
        migrations.RemoveField(
            model_name="article",
            name="surprise_finding",
        ),
    ]
