# Generated by Django 5.2.8 on 2025-11-29 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0008_remove_article_background_context_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleVideo",
            fields=[
                (
                    "article",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="video",
                        serialize=False,
                        to="articles.article",
                    ),
                ),
                ("file", models.FileField(upload_to="")),
            ],
        ),
    ]
